---
# tasks file for romdir

- name: "{{ my_name }} - Load RetroNAS config"
  include_vars: retronas_vars.yml

- name: "{{ my_name }} - build layout"
  file:
    path: "{{ retronas_path }}/roms/{{ item }}"
    owner: "{{ retronas_user }}"
    group: "{{ retronas_user }}"
    state: directory
    mode: "0775"
  with_items:
    - "acorn/archimedes"
    - "acorn/atom"
    - "acorn/bbcmicro"
    - "acorn/electron"
    - "amstrad/cpc"
    - "amstrad/pcw"
    - "apple/appleii"
    - "apple/macintosh"
    - "atari/2600"
    - "atari/5200"
    - "atari/7800"
    - "atari/800"
    - "atari/jaguar"
    - "atari/lynx"
    - "atari/st"
    - "bally/astrocade"
    - "bandai/rx78"
    - "bandai/wonderswan"
    - "bandai/wonderswancolor"
    - "commodore/amiga"
    - "commodore/amigacd32"
    - "commodore/commodore16"
    - "commodore/commodore64"
    - "commodore/commodore128"
    - "commodore/pet"
    - "commodore/vic20"
    - "fujitsu/fmtowns"
    - "fujitsu/fmtownsmarty"
    - "mame/hbmame"
    - "mame/mame"
    - "mattel/aquarius"
    - "mattel/intellivision"
    - "microsoft/msx"
    - "microsoft/xbox"
    - "microsoft/xbox360"
    - "videos/bdiso"
    - "videos/dvdiso"
    - "nec/pc88"
    - "nec/pc98"
    - "nec/pcengine/iso"
    - "nec/pcengine/supergrafx"
    - "nec/pcfx"
    - "nintendo/3ds"
    - "nintendo/ds"
    - "nintendo/famicom"
    - "nintendo/gameandwatch"  
    - "nintendo/gameboy"
    - "nintendo/gameboyadvance"
    - "nintendo/gameboycolor"
    - "nintendo/gamecube/iso"
    - "nintendo/nintendo64"
    - "nintendo/superfamicom"
    - "nintendo/virtualboy" 
    - "nintendo/wii"
    - "other/antonic_galaksija"
    - "other/cambridge_edsac"
    - "other/coleco_colecovision"
    - "other/compukit_uk101"
    - "other/electronika_bk"
    - "other/emerson_arcadia2001"
    - "other/fairchild_channelf"
    - "other/generalinstrument_ay38500"
    - "other/intel_x86"
    - "other/interact_homecomputer"
    - "other/interton_vc4000"
    - "other/jupiter_ace"
    - "other/magnavox_odyssey"
    - "other/magnavox_odyssey2"
    - "other/milesgordon_samcoupe"
    - "other/mits_altair8800"
    - "other/pelvarazdin_orao"
    - "other/radio_86rk"
    - "other/searle_multicomp"
    - "other/sord_m5"
    - "other/specialist_mx"
    - "other/spectravideo_sv328"
    - "other/tangerine_oric"
    - "other/tatung_einstein"
    - "other/tesla_ondraspo186"
    - "other/tesla_pmd85"
    - "other/texasinstruments_ti994a"
    - "other/videotechnology_vtechlaser"
    - "other/vector06c"
    - "other/vectrex"
    - "other/zxevolution"
    - "sega/32x"
    - "sega/gamegear"
    - "sega/dreamcast"
    - "sega/mastersystem"
    - "sega/megacd"
    - "sega/megadrive"
    - "sega/saturn"
    - "sharp/mz"
    - "sharp/x68000"
    - "sinclair/ql"
    - "sinclair/zx81"
    - "sinclair/zxspectrum"
    - "snk/neogeo"
    - "snk/neogeopocket"
    - "snk/neogeopocketcolor"
    - "sony/playstation1/iso"
    - "sony/playstation2/cd"
    - "sony/playstation2/dvd"
    - "sony/playstation3/games"
    - "sony/playstation3/iso"
    - "sony/playstationportable/iso"
    - "tandy/trs80"
    - "tandy/trs80colorcomputer1"
    - "tandy/trs80colorcomputer2"
    - "tandy/trs80colorcomputer3"
    - "tandy/trs80mc10"

- name: "{{ my_name }} - build Nintendo symlinks"
  file:
    src: "{{ item.src }}"
    dest: "{{ retronas_path }}/roms/nintendo/{{ item.dest }}"
    owner: "{{ retronas_user }}"
    group: "{{ retronas_user }}"
    state: link
  with_items:
    - { src: "famicom", dest: "nes" }
    - { src: "superfamicom", dest: "snes" }

- name: "{{ my_name }} - build Sega symlinks"
  file:
    src: "{{ item.src }}"
    dest: "{{ retronas_path }}/roms/sega/{{ item.dest }}"
    owner: "{{ retronas_user }}"
    group: "{{ retronas_user }}"
    state: link
  with_items:
    - { src: "megadrive", dest: "genesis" }
    - { src: "megacd", dest: "segacd" }

- name: "{{ my_name }} - build NEC symlinks"
  file:
    src: "{{ item.src }}"
    dest: "{{ retronas_path }}/roms/nec/{{ item.dest }}"
    owner: "{{ retronas_user }}"
    group: "{{ retronas_user }}"
    state: link
  with_items:
    - { src: "pcengine", dest: "turbografx16" }
    - { src: "pcengine/iso", dest: "pcenginecd" }
    - { src: "pcengine/iso", dest: "turbografxcd" }
